Extend multi-platform support (#298)
* Test Python-3.8 on Linux

* Run tests on macOS

* Turn off tests w/ Python 3.5-3.6-3.7 on Linux

* Travis on macOS: don't install GCC

* Travis: use pip3 & python3 instead of pip & python

* Travis: use 'python3 -m pip' instead of 'pip3'

* Travis: define PYTHON environment variable

This is set to 'python' for Travis' and Anaconda's installations,
and to 'python3' for Homebrew's installation.

* Travis: pass --oversubscribe to mpiexec

* Travis: only use --oversubscribe for macOS

* Remove comma after 'print *' without arguments

Some Fortran compilers (like the one on Travis for macOS) raise this error:

> /Users/travis/build/pyccel/pyccel/tests/pyccel/scripts/import_syntax/__pyccel__/from_mod_import.f90:36:10:
>
>    36 |   print *,
>
>       |          1
>
> Error: Comma after * at (1) not allowed without I/O list

* Update README with Windows instructions

* Update README.rst

* Revert "Turn off tests w/ Python 3.5-3.6-3.7 on Linux"

This reverts commit 69296df6c25298041c5d4291a515981a01fea2cb.

* Update version

Co-authored-by: Christopher Albert <albert@alumni.tugraz.at>